name: CI

on:
  push:
    branches:
    - master

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]    # ubuntu-18.04, windows-2019, macOS-10.14
        go: ['1.12.x', '1.13.x']
    runs-on: ${{ matrix.os }}
    env:
      GOPROXY: https://proxy.golang.org
      HUGO_BUILD_TAGS: extended
      CI: true      # https://github.com/jakejarvis/hugo-custom/blob/f4706331e55d3c78d66a3df43e9c1a0bb58a3590/releaser/git_test.go#L69
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@master
      with:
        go-version: ${{ matrix.go }}
        path: ./src/github.com/${{ github.repository }}
    - name: Run tests
      shell: bash     # force Git Bash shell on windows
      timeout-minutes: 20
      run: |
        export GOPATH=$HOME/go        # https://github.com/actions/setup-go/issues/12
        export GOBIN=$GOPATH/bin
        export PATH=$PATH:$GOPATH
        export PATH=$PATH:$GOBIN
        go get github.com/magefile/mage
        go mod download || true
        mage -v test
        mage -v check
        mage -v hugo
        ./hugo version
        ./hugo -s docs/
        ./hugo --renderToMemory -s docs/

  docker:
    needs: [test]    # only run if tests succeed
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Docker Hub login
      run: |
        echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u jakejarvis --password-stdin https://index.docker.io/v1/
    - name: Build images
      run: |
        docker build -t jakejarvis/hugo-custom:latest -f Dockerfile .
    - name: Push images
      run: |
        docker push jakejarvis/hugo-custom:latest
    - name: Docker Hub logout
      run: |
        docker logout
