name: Docker Hub

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Docker Hub login
      run: |
        echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u jakejarvis --password-stdin https://index.docker.io/v1/
    - name: Build images
      run: |
        docker build -t jakejarvis/hugo-custom:latest -f Dockerfile .
    - name: Push images
      run: |
        docker push jakejarvis/hugo-custom:latest
    - name: Docker Hub logout
      run: |
        docker logout
