name: Test Auto-Release

on:
  push:
    branches:
    - release-action

jobs:
  release:
    runs-on: ubuntu-latest   # for compatibility
    container:
      image: docker://netlify/build:xenial
      options: -u 0
      volumes:
        - /github/home:/opt/buildhome
        - /home/runner/work/hugo-custom/hugo-custom:/opt/repo
    steps:
    - run: whoami
