name: Test Auto-Release

on:
  push:
    branches:
    - release-action

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: docker://netlify/build:xenial
      env:
        GO_VERSION: 1.13
      options: --user root
      volumes:
      - /github/home:/opt/buildhome
      - /home/runner/work/hugo-custom/hugo-custom:/opt/repo
    steps:
    - uses: actions/checkout@master
    - run: whoami
    - name: Gimme Go 1.13
      run: |
        eval "$(gimme 1.13)"
        go version
        find / -name "magefile.go"
        cd /__w/hugo-custom/hugo-custom
        ls
    #- run: go version
    #- run: go env GOPATH
