name: Test Auto-Release

on:
  push:
    branches:
    - release-action

jobs:
  release:
    runs-on: ubuntu-16.04   # for compatibility
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@master
      with:
        go-version: '1.13'
    # - run: go env 
    # - run: strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
    - name: Build binary
      run: |
        go get -u github.com/magefile/mage
        $(go env GOPATH)/bin/mage hugo
        HUGO_BUILD_TAGS=extended $(go env GOPATH)/bin/mage install
        cp $(go env GOPATH)/bin/hugo ./hugo-extended
    - name: Make sure binary's OK
      run: chmod +x ./hugo-extended && ./hugo-extended version
    - uses: actions/upload-artifact@master
      with:
        name: hugo-extended_Linux-64bit
        path: ./hugo-extended
    - name: Create release
      id: create_release
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v0.53-DEV
        release_name: v0.53-DEV
        draft: false
        prerelease: false
    - name: Upload release
      uses: actions/upload-release-asset@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}   # https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./hugo-extended
        asset_name: hugo-extended_Linux-64bit
        asset_content_type: application/octet-stream
