name: Test Auto-Release

on:
  push:
    branches:
    - release-action

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: docker://netlify/build:xenial
      options: --user root
      volumes:
      - /github/home:/opt/buildhome
      - /home/runner/work/hugo-custom/hugo-custom:/opt/repo
    steps:
    - uses: actions/checkout@master
    - run: whoami
    - name: Gimme Go 1.13
      run: eval $(gimme 1.13)
    - run: go version
    - run: go env GOPATH
