name: Test Auto-Release

on:
  push:
    branches:
    - release-action

jobs:
  release:
    runs-on: ubuntu-latest   # for compatibility
    container:
      image: docker://netlify/build:xenial
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@master
      with:
        go-version: '1.13'
    # - run: go env 
    # - run: strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
    - name: Build binary
      run: |
        go get -u github.com/magefile/mage
        $(go env GOPATH)/bin/mage hugo
        HUGO_BUILD_TAGS=extended $(go env GOPATH)/bin/mage install
        cp $(go env GOPATH)/bin/hugo ./hugo-extended
    - name: Make sure binary's OK
      run: chmod +x ./hugo-extended && ./hugo-extended version
    - uses: actions/upload-artifact@master
      with:
        name: hugo-extended_Linux-64bit
        path: ./hugo-extended
